
"$schema" = "./love.schema.json"

[audio]
# Keep background music playing when opening LOVE (iOS and Android only)
mix_with_system = false

[project]
# Name of the project
name = "Itsukai"
# Enable the accelerometer on iOS and Android by exposing it as a Joystick
accelerometer_joystick = false

[window]
title = "Itsukai"
width = 816
height = 624